import {Components} from "swagger-jsdoc";

export const rolesSchemas: Components = {
    Rol: {
        type: 'object',
        required: ["name", "description"],
        properties: {
            name: {
                type: 'string'
            },
            description: {
                type: 'string'
            },
        }
    },
    RolUpdate: {
        type: 'object',
        required: ["description"],
        properties: {
            description: {
                type: 'string'
            },
        }
    },
    Roles: {
        type: 'object',
        properties: {
            name: {
                type: 'string'
            },
            description: {
                type: 'string'
            },
            id: {
                type: 'string',
                format: 'id-mongo'
            }
        }
    }
}

export const rolesExamples: Components = {
    rolesResponse: {
        summary: 'Roles of our application',
        value: [
            {
                "name": "ADMIN",
                "description": "Administrator role with full privileges and complete access to the system. Responsible for managing and supervising all operations of the system, including the management of cocktails, bartenders, bookings, and other users.",
                "id": "64cbd63ea0ebec5e5af4f5bf"
            },
            {
                "name": "BARTENDER",
                "description": "Role for professional bartenders. Bartenders have access to functions required to manage their profile, view assigned bookings, and update their availability for events.",
                "id": "64cbd66da0ebec5e5af4f5c3"
            },
            {
                "name": "CUSTOMER",
                "description": "Role for registered users who can make bookings for bartender services and explore available cocktails on the platform. They can view and manage their own bookings and profiles.",
                "id": "64cbd74fa0ebec5e5af4f5c9"
            },
            {
                "name": "VISITOR",
                "description": "Role for non-registered or website visitors. Visitors can explore the list of cocktails and view general information, but they do not have access to booking functions or certain features exclusive to registered users.",
                "id": "64cbd75fa0ebec5e5af4f5cb"
            },
            {
                "name": "EVENT MANAGER",
                "description": "Role for users with specific event management functions. They have access to bookings, bartender profiles, and event details to coordinate bartender activities at specific events.",
                "id": "64cbd770a0ebec5e5af4f5cd"
            },
            {
                "name": "DATA ANALYST",
                "description": "Role for users responsible for analyzing data generated by the system. They have access to reports and statistics to gain insights into booking trends, cocktail preferences, among others.",
                "id": "64cbd78ca0ebec5e5af4f5cf"
            },
            {
                "name": "CUSTOMER SUPPORT",
                "description": "Role for users responsible for providing assistance and technical support to customers. They can receive and respond to queries, help with technical issues, and provide solutions to users.",
                "id": "64cbdae7a0ebec5e5af4f5d1"
            },
            {
                "name": "MARKETING",
                "description": "Role for users in charge of marketing and promotional strategies. They have access to featured cocktail lists and can coordinate marketing campaigns to increase the website's visibility.",
                "id": "64cc635580b0c60ed70ddc0e"
            }
        ]
    },
    rolCreated: {
        summary: 'Create a new rol',
        value: {
            name: "Testing",
            description: "Description testing"
        }
    },
    rolUpdated: {
        summary: 'Update rol for id',
        value: {
            description: "Description testing"
        }
    },
    rolUpdatedShortDescription: {
        summary: 'Update rol for id (short description)',
        value: {
            description: "De"
        }
    },
    rolNameRepeat: {
        summary: 'Create a new rol with name repeat',
        value: {
            name: "Admin",
            description: "Description testing"
        }
    },
    rolCreatedSuccess: {
        summary: 'Create a new rol successfully',
        value: {
            name: "TESTING",
            description: "Description testing",
            createdAt: "2023-08-10T01:28:02.296Z",
            updatedAt: "2023-08-10T01:28:02.296Z",
            id: "64d43d227a02934539309ecd"
        }
    },
    rolUpdatedSuccess: {
        summary: 'Update rol for id successfully',
        value: {
            name: "TESTING",
            description: "Description testing",
            createdAt: "2023-08-10T01:28:02.296Z",
            updatedAt: "2023-08-10T01:28:02.296Z",
            id: "64d43d227a02934539309ecd"
        }
    },
    rolDeletedSuccess: {
        summary: 'Delete rol for id successfully',
        value: {
            name: "TESTING",
            description: "Description testing",
            createdAt: "2023-08-10T01:28:02.296Z",
            updatedAt: "2023-08-10T01:28:02.296Z",
            id: "64d43d227a02934539309ecd"
        }
    },
    rolNameRepeatResponse: {
        summary: 'Error in name repeat or fails in database',
        value: {
            error: "ERROR_CREATE_ROL"
        }
    }
}